Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -27,20 +27,20 @@ jobs:
       - name: install y
         run: sudo apt-get install jq
 
-      # Step 7: Check Quality Gate
-      - name: Check Quality Gate
-        run: |
-          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
-            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Soubarniya_ci-cd")
+      # # Step 7: Check Quality Gate
+      # - name: Check Quality Gate
+      #   run: |
+      #     RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" \
+      #       "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Soubarniya_ci-cd")
           
-          echo "Response: $RESPONSE"
+      #     echo "Response: $RESPONSE"
           
-          STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)
+      #     STATUS=$(echo "$RESPONSE" | jq -r .projectStatus.status)
       
-          if [ "$STATUS" != "OK" ]; then
-            echo "Quality Gate failed: $STATUS"
-            exit 1
-          fi
+      #     if [ "$STATUS" != "OK" ]; then
+      #       echo "Quality Gate failed: $STATUS"
+      #       exit 1
+      #     fi
 
       # Step 4: Set up Go environment
       - name: Set up Go environment
