Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -7,7 +7,6 @@ on:
   pull_request:
     branches:
       - main
-  workflow_dispatch:
 
 jobs:
   test:
@@ -22,15 +21,22 @@ jobs:
           go-version: '1.23.2'
 
       - name: Install dependencies
-        run: |
-          go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
-          go get -v ./...
+        run: go get .
+      - name: Build
+        run: go build -v ./...
+      - name: Test with the Go CLI
+        run: go test
 
-      - name: Install the application
-        run: go install ./...
+      # - name: Install dependencies
+      #   run: |
+      #     go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
+      #     go get -v ./...
 
-      - name: Run tests
-        run: go test -v ./... || exit 1  # Fail the job if tests fail
+      # - name: Install the application
+      #   run: go install ./...
+
+      # - name: Run tests
+      #   run: go test -v ./... || exit 1  # Fail the job if tests fail
 
   # Build the application and upload artifact
   build:
