Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -27,7 +27,6 @@ jobs:
         run: |
           go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
           go get -v ./...
-
       - name: Install the application
         run: go install ./...
 
@@ -77,9 +76,13 @@ jobs:
       - name: Read version from VERSION file
         id: read_version
         run: |
-          VERSION=$(cat VERSION | xargs)
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
-
+          if [ -f VERSION ]; then
+            VERSION=$(cat VERSION | xargs)
+            echo "VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "VERSION file not found!"
+            exit 1
+          fi
       - name: Build and push Docker image
         run: |
           docker build -t manisankardivi/new:${{ env.VERSION }} .
@@ -95,14 +98,17 @@ jobs:
 
       - name: Read version from VERSION file
         run: |
-          # Read the version from the VERSION file
-          VERSION=$(cat VERSION)
-          echo "Version extracted: $VERSION"
-          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save version to environment variable
-  
+          if [ -f VERSION ]; then
+            VERSION=$(cat VERSION)
+            echo "Version extracted: $VERSION"
+            echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save version to environment variable
+          else
+            echo "VERSION file not found!"
+            exit 1
+          fi
+
       - name: Checkout Kubernetes repo
         run: |
-          # Clone the k8s-repo repository
           git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/manisankar-divi/k8s-repo.git
           cd k8s-repo
           
@@ -119,7 +125,7 @@ jobs:
           # Check for any changes in the file and commit if there are updates
           git status
           git diff
-  
+
       - name: Check for changes and commit if updated
         run: |
           cd k8s-repo
@@ -142,13 +148,23 @@ jobs:
             
             # Push the changes to the repository
             git push origin main
-          fi
+
   create_pull_request:
     runs-on: ubuntu-latest
     needs: k8s-manifest-files_update  # Only run after Kubernetes manifest is updated
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Check if there are new commits between staging and main
+        run: |
+          git fetch origin
+          if git rev-list --count origin/main..origin/staging | grep -q '^[1-9][0-9]*$'; then
+            echo "New commits found, proceeding with PR creation."
+          else
+            echo "No new commits between staging and main, skipping PR creation."
+            exit 0
+          fi
 
       - name: Open PR
         id: open_pr
@@ -159,6 +175,6 @@ jobs:
           to-branch: main
           repository-owner: manisankar-divi
           repository: go-project
-          
+
       - name: Echo mergeable PR number
         run: echo ${{ steps.open_pr.outputs.pull_number }}
