Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -21,22 +21,15 @@ jobs:
           go-version: '1.23.2'
 
       - name: Install dependencies
-        run: go get .
-      - name: Build
-        run: go build -v ./...
-      - name: Test with the Go CLI
-        run: go test
+        run: |
+          go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
+          go get -v ./...
 
-      # - name: Install dependencies
-      #   run: |
-      #     go mod tidy  # Ensure the go.mod and go.sum files are up-to-date
-      #     go get -v ./...
+      - name: Install the application
+        run: go install ./...
 
-      # - name: Install the application
-      #   run: go install ./...
-
-      # - name: Run tests
-      #   run: go test -v ./... || exit 1  # Fail the job if tests fail
+      - name: Run tests
+        run: go test -v ./... || exit 1  # Fail the job if tests fail
 
   # Build the application and upload artifact
   build:
